'use client';
import {useEffect,useState} from 'react';
import {csvCell} from '@/lib/crm';
type Lead={id:string;name:string;email:string;phone:string;created_at:string;primary_profile:string;status:string;whatsapp_consent:boolean;scores:Record<string,number>};
type Summary={total:number;new:number;reviewed:number;whatsapp:number;days:{label:string;count:number}[];profiles:{name:string;count:number}[]};
type View='overview'|'leads'|'customers'|'recovery'|'acquisition';
const views:{id:View;icon:string;label:string;sub:string}[]=[{id:'overview',icon:'▦',label:'Overview',sub:'Business performance at a glance'},{id:'leads',icon:'◉',label:'Leads',sub:'Your shared lead database'},{id:'customers',icon:'✓',label:'Customers',sub:'Paid customer records'},{id:'recovery',icon:'↗',label:'Recovery',sub:'Follow-up and payment recovery'},{id:'acquisition',icon:'⌁',label:'Acquisition',sub:'Sources and campaigns'}];
async function request(path:string,input?:unknown){const res=await fetch('/api/'+path,{cache:'no-store',...(input===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to load records.');return data;}
export default function Crm({email,onSignOut}:{email:string;onSignOut:()=>Promise<void>}){
 const [view,setView]=useState<View>('overview'),[summary,setSummary]=useState<Summary|null>(null),[rows,setRows]=useState<Lead[]>([]),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[total,setTotal]=useState(0),[busy,setBusy]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;setBusy(true);setError('');setRows([]);setSummary(null);const params=new URLSearchParams({page:String(view==='leads'?page:0),q:view==='leads'?search:'',status:view==='leads'?filter:'all'});Promise.all([request('staff/summary'),request('staff/assessments?'+params)]).then(([s,l])=>{if(active){setSummary(s);setRows(l.assessments);setTotal(l.total)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[view,page,search,filter,revision]);
 const selected=views.find(v=>v.id===view)!;const top=summary?.profiles.reduce((best,p)=>p.count>best.count?p:best,{name:'—',count:0});
 function exportPage(){if(!rows.length)return;const data=[['Name','Email','Phone','Quotient','Status','WhatsApp consent','Captured'],...rows.map(r=>[r.name,r.email,r.phone,r.primary_profile,r.status,r.whatsapp_consent?'Yes':'No',r.created_at])];const url=URL.createObjectURL(new Blob(['\uFEFF'+data.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=url;link.download='skin-quotient-leads-page-'+(page+1)+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function review(id:string){setBusy(true);setError('');try{await request('staff/review',{id,status:'reviewed'});setRevision(r=>r+1)}catch(e){setError(e instanceof Error?e.message:'Unable to save review.');setBusy(false)}}
 function table(items:Lead[],detailed=false){return <div className="table-wrap"><table><thead><tr><th>Lead</th><th>Contact</th><th>Quotient</th><th>Status</th><th>WhatsApp consent</th><th>Captured</th>{detailed&&<th>Review</th>}</tr></thead><tbody>{items.length?items.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td><div>{r.email}</div><div className="card-meta">{r.phone}</div></td><td><span className="badge gray">{r.primary_profile.toUpperCase()}</span></td><td><span className={'badge '+(r.status==='reviewed'?'green':'amber')}>{r.status==='reviewed'?'Reviewed':'New'}</span></td><td>{r.whatsapp_consent?'Opted in':'Not opted in'}</td><td>{new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeZone:'Asia/Kolkata'}).format(new Date(r.created_at))}</td>{detailed&&<td><button className="btn" disabled={busy||r.status==='reviewed'} onClick={()=>void review(r.id)}>{r.status==='reviewed'?'Reviewed':'Mark reviewed'}</button></td>}</tr>):<tr><td colSpan={detailed?7:6}><div className="empty"><strong>{busy?'Loading records…':'No leads to display'}</strong>{error?'Records could not be loaded.':search||filter!=='all'?'Try another search or filter.':'New quiz submissions will appear here.'}</div></td></tr>}</tbody></table></div>}
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-main">skin quotient</div><div className="brand-sub">ADMIN / GROWTH OS</div></div><nav className="nav" aria-label="CRM sections">{views.map(v=><button key={v.id} className={view===v.id?'active':''} aria-current={view===v.id?'page':undefined} onClick={()=>{setView(v.id);setPage(0)}}><span className="ico" aria-hidden="true">{v.icon}</span><span>{v.label}</span></button>)}</nav><div className="sidebar-bottom"><div className="status"><span className="dot"/> {error?'Connection needs attention':busy?'Connecting…':'Secure database connected'}</div><div className="staff-email">{email}</div></div></aside><main className="main"><header className="topbar"><div><div className="greeting">Skin Quotient · Staff workspace</div><div className="page-title">{selected.label}</div><div className="page-sub">{selected.sub}</div></div><div className="top-actions">{(view==='leads'||view==='overview')&&<button className="btn" disabled={busy||!rows.length} onClick={exportPage}>Export page CSV</button>}<button className="btn" disabled={busy} onClick={()=>setRevision(r=>r+1)}>Refresh</button><button className="btn" onClick={()=>void onSignOut().catch(e=>setError(e.message))}>Sign out</button></div></header><div className="content"><div role="status" aria-live="polite">{error&&<div className="crm-error">{error} <button className="btn" onClick={()=>setRevision(r=>r+1)}>Retry</button></div>}</div>
 {view==='overview'&&<section className="view active"><div className="grid-kpi">{[
 ['Leads',summary?.total,'Captured profiles','◉','green'],['New leads',summary?.new,'Awaiting review','↗','amber'],['Reviewed',summary?.reviewed,'Completed staff reviews','✓','green'],['WhatsApp opt-ins',summary?.whatsapp,'Permission to follow up','◌','purple'],['Customers','—','Payments not connected','✓',''],['Revenue','—','Payments not connected','₹','purple'],['Visits','—','Visitor tracking not connected','⌁',''],['Top quotient',top?.count?top.name.toUpperCase():'—','Most common profile','◈','purple']
 ].map(([label,value,foot,icon,tone])=><div className={'kpi '+tone} key={String(label)}><div className="kpi-top"><div className="kpi-label">{label}</div><div className="kpi-icon" aria-hidden="true">{icon}</div></div><div className="kpi-value">{value??'—'}</div><div className="kpi-foot">{foot}</div></div>)}</div><div className="section-grid"><div className="card"><div className="card-head"><div><div className="card-title">Lead review funnel</div><div className="card-meta">All records you have permission to access</div></div></div><div className="card-body"><div className="funnel">{[['Captured',summary?.total],['Awaiting review',summary?.new],['Reviewed',summary?.reviewed],['WhatsApp opt-ins',summary?.whatsapp]].map(([label,n])=><div className="f-row" key={String(label)}><div className="f-label">{label}</div><div className="bar"><span style={{width:summary?Math.min(100,Number(n)/Math.max(summary.total,1)*100)+'%':'0%'}}/></div><div className="f-num">{n??'—'}</div></div>)}</div></div></div><div className="card"><div className="card-head"><div><div className="card-title">Leads · last 7 days</div><div className="card-meta">Captured lead volume · India time</div></div></div><div className="card-body"><div className="chart">{summary?.days.map((d,i)=><div className="bar-day" key={i}><small>{d.count}</small><div className={'bar-fill '+(i===6?'today':'')} style={{height:Math.max(3,d.count/Math.max(...summary.days.map(x=>x.count),1)*150)}}/><small>{d.label}</small></div>)}</div></div></div></div><div className="section-grid"><div className="card"><div className="card-head"><div className="card-title">Recent leads</div><button className="btn" onClick={()=>setView('leads')}>View all</button></div>{table(rows.slice(0,5))}</div><div className="card"><div className="card-head"><div className="card-title">Quotient breakdown</div></div><div className="card-body"><div className="source-list">{summary?.profiles.map(p=><div className="source-row" key={p.name}><div className="source-name">{p.name}</div><div className="source-bar"><span style={{width:p.count/Math.max(summary.total,1)*100+'%'}}/></div><div>{p.count}</div></div>)}</div></div></div></div></section>}
 {view==='leads'&&<section className="view active"><div className="toolbar"><div><div className="card-title">Lead database</div><div className="card-meta">{busy?'Loading…':total+' matching profiles'} · 25 per page</div></div><form className="filters" onSubmit={e=>{e.preventDefault();setSearch(query);setPage(0)}}><input className="input" aria-label="Search name or email" placeholder="Search name or email" value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/><button className="btn" disabled={busy}>Search</button><select className="select" aria-label="Lead status" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}><option value="all">All statuses</option><option value="new">New</option><option value="reviewed">Reviewed</option></select></form></div><div className="card table-card">{table(rows,true)}</div><div className="pagination"><button className="btn" disabled={busy||page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(total/25))}</span><button className="btn" disabled={busy||(page+1)*25>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>}
 {view==='customers'&&<section className="view active"><div className="toolbar"><div><div className="card-title">Customers</div><div className="card-meta">Verified paid customer records</div></div></div><div className="card"><div className="empty"><strong>Payments are not connected yet</strong>Verified customers, purchases and revenue will appear here after payment integration is enabled.</div></div></section>}
 {view==='recovery'&&<section className="view active"><div className="toolbar"><div><div className="card-title">Payment recovery</div><div className="card-meta">Follow up on verified payment activity</div></div></div><div className="card"><div className="card-head"><div className="card-title">WhatsApp queue</div><div className="card-meta">No messages sent automatically</div></div><div className="empty"><strong>Payment recovery is not active</strong>Payments are currently disabled. You can review contact details and WhatsApp consent in Leads.<div className="empty-action"><button className="btn" onClick={()=>setView('leads')}>Open leads</button></div></div></div></section>}
 {view==='acquisition'&&<section className="view active"><div className="subnav"><span className="badge gray">Sources & campaigns</span></div><div className="section-grid"><div className="card"><div className="card-head"><div className="card-title">UTM source performance</div></div><div className="empty"><strong>Attribution is not connected yet</strong>Source and campaign results will appear once tracking is enabled.</div></div><div className="card"><div className="card-head"><div className="card-title">Tracking status</div></div><div className="card-body"><p className="tracking-note">Assessment leads are saved securely. Visitor analytics, advertising spend and campaign attribution are not currently collected.</p></div></div></div></section>}
 </div></main></div>;
}
