'use client';
import {useEffect,useState,FormEvent} from 'react';
import Crm from './Crm';
type RecordItem={id:string;name:string;created_at:string;primary_profile:string;phone?:string;email?:string;status?:string;whatsapp_consent?:boolean;scores:Record<string,number>;assessment_reviews?:{status:string}|{status:string}[]};
async function api(path:string,input?:unknown){const response=await fetch('/api/'+path,{cache:'no-store',...(input===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again.');return data;}
export default function Account(){
 const [ready,setReady]=useState(false),[enabled,setEnabled]=useState(false),[passwordEnabled,setPasswordEnabled]=useState(false),[password,setPassword]=useState(''),[email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [me,setMe]=useState<{email:string;staff:boolean;staffVerified:boolean}|null>(null),[records,setRecords]=useState<RecordItem[]>([]),[factor,setFactor]=useState(''),[qr,setQr]=useState(''),[page,setPage]=useState(0),[total,setTotal]=useState(0);
 async function refresh(currentPage=0){const user=await api('me');setMe(user);if(user.staff&&!user.staffVerified){const data=await api('staff/mfa');setFactor(data.factors[0]?.id||'');}const data=await api(user.staffVerified?'staff/assessments?page='+currentPage:'assessments');setRecords(data.assessments);setTotal(data.total||0);setPage(currentPage);}
 useEffect(()=>{let active=true;(async()=>{try{const status=await api('status');if(!active)return;setEnabled(status.configured&&status.emailEnabled);setPasswordEnabled(status.configured);if(status.configured){try{await refresh()}catch(error){if(error instanceof Error&&!error.message.startsWith('Sign in'))setNotice(error.message)}}else setNotice('Account setup is in progress. Sign-in is not open yet.');}catch{setNotice('Unable to connect. Please reload this page.')}finally{if(active)setReady(true)}})();return()=>{active=false}},[]);
 async function run(action:()=>Promise<void>){setBusy(true);setNotice('');try{await action()}catch(error){setNotice(error instanceof Error?error.message:'Please try again.')}finally{setBusy(false)}}
 function login(event:FormEvent){event.preventDefault();void run(async()=>{const data=await api('auth/email',{email});setSent(true);setNotice(data.message)})}
 function passwordLogin(event:FormEvent){event.preventDefault();void run(async()=>{try{await api('auth/password',{email,password});await refresh()}finally{setPassword('')}})}
 function verify(event:FormEvent){event.preventDefault();void run(async()=>{await api('auth/verify',{email,code});setCode('');await refresh()})}
 if(ready&&me?.staffVerified)return <Crm email={me.email} onSignOut={async()=>{await api('auth/logout',{});setMe(null);setRecords([]);setQr('');setFactor('');setSent(false)}}/>;
 return <main className="auth-shell"><header><a className="brand" href="/">Skin Quotient</a><a href="/assessment.html">Take the assessment</a></header><h1>{me?.staff?'Staff account':'Staff login'}</h1><p className="intro">Restricted staff access. Customers can complete the assessment without signing in.</p><p role="status" aria-live="polite" className="notice">{notice}</p>
 {!ready?<p>Checking your account…</p>:!me?<section><h2>Sign in to admin</h2><form onSubmit={passwordLogin}><label htmlFor="staff-email">Email address</label><input id="staff-email" type="email" autoComplete="username" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} required/><label htmlFor="staff-password">Password</label><input id="staff-password" type="password" autoComplete="current-password" maxLength={256} value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={busy||!passwordEnabled}>Sign in</button></form><h2>Or sign in with an email link</h2>{!enabled&&<p className="notice">Email sign-in is being configured. Nothing entered here will be sent while it is unavailable.</p>}<form onSubmit={login}><label htmlFor="email">Email address</label><input id="email" type="email" autoComplete="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} required/><button disabled={busy||!enabled}>Send sign-in email</button></form>{sent&&<form onSubmit={verify}><p>Open the link in this browser. If your email contains a code, enter it below.</p><label htmlFor="code">Email code</label><input id="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6,8}" value={code} onChange={e=>setCode(e.target.value)} required/><button disabled={busy}>Verify code</button></form>}</section>:<><div className="session"><span>{me.email}</span><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{await api('auth/logout',{});setMe(null);setRecords([]);setQr('');setFactor('');setSent(false)})}>Sign out</button></div>
 {me.staff&&!me.staffVerified&&<section><h2>Verify staff access</h2><p>Use an authenticator app to open customer records.</p>{!factor?<button disabled={busy} onClick={()=>void run(async()=>{const data=await api('staff/mfa/enroll',{});setFactor(data.factorId);setQr(data.qr)})}>Set up authenticator</button>:<>{qr&&<><p>Scan this code in your authenticator app. Keep it private.</p><img className="qr" src={qr} alt="Authenticator setup QR code"/></>}<form onSubmit={event=>{event.preventDefault();void run(async()=>{await api('staff/mfa/verify',{factorId:factor,code});setCode('');setQr('');await refresh()})}}><label htmlFor="mfa">Authenticator code</label><input id="mfa" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" value={code} onChange={e=>setCode(e.target.value)} required/><button disabled={busy}>Verify staff session</button></form></>}</section>}
 <section><h2>{me.staffVerified?'Assessment review queue':'Saved assessments'}</h2><p>Results are based on the questionnaire, and are not a diagnosis or a clinician-approved treatment plan.</p>{records.length===0?<p>No assessments to display.</p>:records.map(record=>{const review=Array.isArray(record.assessment_reviews)?record.assessment_reviews[0]:record.assessment_reviews;return <article key={record.id}><h3>{record.name}</h3><p>{new Date(record.created_at).toLocaleDateString()} · Main questionnaire signal: {record.primary_profile}</p><dl>{Object.entries(record.scores).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>{me.staffVerified&&<><p>{record.email} · {record.phone||'No phone provided'} · WhatsApp follow-up: {record.whatsapp_consent?'opted in':'not opted in'} · Review: {record.status||'new'}</p><button className="secondary" disabled={busy||record.status==='reviewed'} onClick={()=>void run(async()=>{await api('staff/review',{id:record.id,status:'reviewed'});await refresh(page)})}>Mark reviewed</button></>}</article>})}{me.staffVerified&&<nav aria-label="Review pages"><button disabled={busy||page===0} onClick={()=>void run(()=>refresh(page-1))}>Previous</button><span>Page {page+1}</span><button disabled={busy||(page+1)*25>=total} onClick={()=>void run(()=>refresh(page+1))}>Next</button></nav>}</section></>}
 <footer><a href="/privacy-policy.html">Privacy</a><span>Online payment and booking are not open yet.</span></footer></main>;
}


